### ISSUE TITLE
Incorrect response from gree U-crown after  {"t": "scan"}

### ISSUE THREAD

**Issue by RonGroen** [tomikaa87/gree-remote#11]
I have a Gree U-crown installed: https://www.gree.nl/nl/12-producten/split/33-u-crown

After the {"t": "scan"} I get a incorrect formatted response like: 
Received packet of size 347
From 192.168.0.12, port 7000

Packet contents:
0-->t 74
1--> 0
2-->p 70
3-->a 61
4-->c 63
5-->k 6B
6--> 0
7-->i 69
8--> 0
9-->1 31
10--> 0
11-->u 75
12-->i 69
13-->d 64
Position, char value en hex number.
 
I am using the software on an arduino mega.
My computer can not run QT (Ubuntu 14.04).
Can you please give me a hint?

With kind regards
Ron Groen
The Netherlands.

**Comment by tomikaa87** [comment]
Hi,

Sorry for the (very) late answer. 

What I see is that the response is not JSON formatted, but the fields that supposed to be in the response are there. How did you try to communicate with the AC unit? What framework/language did you use? I had success with C++/Qt, C# and Python as well.

Also, in my opinion, Ubuntu 14.04 has proper Qt packages in the repository, you just have to install them using `apt-get`. Probably they don't have the latest version for that distribution, but almost any 5.x version will do the trick.

One other idea is they switched from the traditional JSON format to a custom one which uses the `0` byte to separate the keys from their values as well as the key-value pairs from each other. If that's the case, you must implement a new packet parser for that format. If you'd like just send some request and response packets to me and I can implement it for you.

**Comment by tomikaa87** [comment]
@RonGroen any updates on this issue?

**Comment by RonGroen** [comment]
tomikaa87 was right. Every thing is working fine here.

**Comment by tomikaa87** [comment]
Awesome! 👍

**Comment by borrelan** [comment]
@RonGroen I'm not sure how to contact you directly. Is there any way you could share the code that worked for you?

**Comment by RonGroen** [comment]
> @RonGroen I'm not sure how to contact you directly. Is there any way you could share the code that worked for you?
Thank you for your response borrelan. I solved the problem a long time ago, but I forgot the save this issue.
