### ISSUE TITLE
no support for firmware v2

### ISSUE THREAD

**Issue by mybays** [tomikaa87/gree-remote#14]
It's only support my KFR-35GW ,which firmware version is V3.31,doesn't work for KFR-26GW,which firmware version is V2

**Comment by tomikaa87** [comment]
I think the firmware version doesn't matter much. Mine is 2.25 and works fine. Does it work with the original Gree app? Can you capture the network traffic between the app and the unit?

**Comment by mybays** [comment]
After capture the network traffic and drcrypt,I found that V2 firmware only contain mac segment,no id segment,replace id segment with mac,now I can control it.
