### ISSUE TITLE
Possibility to stop home talking

### ISSUE THREAD

**Issue by emtek-at** [tomikaa87/gree-remote#15]
Hello,
I have programmed a dummy server to which the devices can connect, so you can block internet traffic in your firewall. There is also a Config Tool to set the new remote host in the Device.
[https://github.com/emtek-at/GreeAC-DummyServer](url)
[https://github.com/emtek-at/GreeAC-ConfigTool](url)

**Comment by sm4rk0** [comment]
Thanks! This is a great hack!
I assume the only drawback is that you can't remote control the devices via cloud when using DummyServer.

Here are the working (clickable) URLs:
https://github.com/emtek-at/GreeAC-DummyServer
https://github.com/emtek-at/GreeAC-ConfigTool

**Comment by emtek-at** [comment]
You're right, the original apps do not work anymore, but if you connect the devices to a smart home control like OpenHab, you can use their online service or a vpn tunnel.

**Comment by sm4rk0** [comment]
Right. That's why I'm watching this repo (:

**Comment by tomikaa87** [comment]
A few weeks ago I tried simply adding the IP address - that the units use to send the heartbeat to - to my firewall and block all traffic. It works fine and the units remained responsive, no issues so far.

**Comment by VeeM** [comment]
Hello @tomikaa87 and @emtek-at,
Does the AC still sending the data to the default server (over the internet) after changing the remote host? I want to figure out if it mandatory to block manually blocks traffic via firewall or it's just to be on the safe side...
Thanks in advance!

**Comment by emtek-at** [comment]
@tomikaa87 maybe you have an other firmware which is more fault tollerant then mine. My devices stop responding.
@VeeM if you change the remote host, all traffic will be directed to this location. So it's not necessary to block traffic via firewall, but you can if you want to.

**Comment by tomikaa87** [comment]
@sm4rk0 I've linked your DummyServer into the documentation: https://github.com/tomikaa87/gree-remote/commit/294c0cd7432e848ee26c1e1dd9ee45f2f0fae761
