### ISSUE TITLE
Add SwingLfRig values to readme

### ISSUE THREAD

**Issue by mvmn** [tomikaa87/gree-remote#18]
The values for SwingLfRig are
- 0 - default (no swing)
- 1 - full swing
- 2 to 6 - fixed leftmost to rightmost

Partial swing doesn't seem to be supported

Figured out on Cooper&Hunter AC by setting swing via "Wifi smart" iOS app and then reading AC status via Gree protocol.

**Comment by tomikaa87** [comment]
Thank you for the info, I've updated the Readme.
