### ISSUE TITLE
How can i get the generic or the device-specific AES key?

### ISSUE THREAD

**Issue by Feuerstein87** [tomikaa87/gree-remote#19]
Hi, i used wireshark and connected/install a new AC but i can`t find the AES Key.
What am I doing wrong?

**Comment by tomikaa87** [comment]
@Feuerstein87 
Hi, the generic AES key is static and embedded into the official application. I've extracted it from the Gree Android app. The device key is different for each unit and must be obtained by running the "binding sequence" (see the documentation).
