### ISSUE TITLE
Lock flag in scan response

### ISSUE THREAD

**Issue by aivus** [tomikaa87/gree-remote#20]
Hello.

Thank you for reverse engineering Gree protocol.
I'm using it in [app](https://apps.athom.com/app/com.gree) for smart home controller Homey.

But I have a question.

Do you have any information about "lock" flag in the scan response package?
Any ideas what does it mean when `lock=1`?

```
{
  "t": "dev",
  "cid": "<MAC address>",
  "bc": "gree",
  "brand": "gree",
  "catalog": "gree",
  "mac": "<MAC address>",
  "mid": "10001",
  "model": "gree",
  "name": "<friendly name of the unit>",
  "series": "gree",
  "vender": "1",
  "ver": "V1.1.13",
  "lock": 0   // <----- THIS
}
```

Thanks

**Comment by tomikaa87** [comment]
Hi @aivus,

The `lock` flag indicates if the device is locked via the remote control. There is a button combination for that, you can check the documentation of your unit.

Regards

**Comment by aivus** [comment]
Didn't found I way to lock HVAC.

I know how to lock remote control by pressing `+` and `-` simultaneously, but it doesn't send any signal to HVAC just lock remote control.

**Comment by tomikaa87** [comment]
My units give a beep when I lock the remote (and it's in visible range). Since there are many units on the market with this WiFi controller, it's possible that the implementation is different in some.

**Comment by mvmn** [comment]
@tomikaa87 ,  did you happen to figure out protocol commands to set WiFi name+password, friendly name of device and/or lock flag?

**Comment by aivus** [comment]
@tomikaa87 to setup WiFi you can use next way:
https://github.com/arthurkrupa/gree-hvac-mqtt-bridge#configuring-hvac-wifi

I'm closing this issue as it was answered.

**Comment by mvmn** [comment]
@aivus, thank you for the info. Do you happen to know also how to set device "friendly name" and/or lock flag?

**Comment by aivus** [comment]
@mvmn no, I don't 
I'm using my internal name in the app instead.
