### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by 4suino** [tomikaa87/gree-remote#21]
Hi! Thank you for the your documentation that is very useful and well explained. I'm trying to interface the gree system via Python but have some issue probably in the requests.
The discover works perfectly and I receive the answers from all splitter but I'm not able to bind any of the five devices.
So, the question is, reading the documentation you wrote about MAC Address that I should use in the tcid and mac fields but when I try the discover I receive different values for these fields.
So, which one I've to use?

The answer on discover in my case is:
Received from ('192.168.0.81', 7000): {"t":"pack","i":1,"uid":0,"cid":"f4911e6fcbdf","tcid":"dc26211e39c8","pack":"LP24Ek0OaYogxs3iQLjL4FxcFMarR4aGOyo8RK7I2p6Ma9lM2RqI/KytvJ32IsGSZXrOr+MakVzzXHbghPeyijnWMzaLQaaw1aFXlE9k71L0cMm8bsr/y4FkxumpRg1tKs/34xhBuMSxXfNfvEgS5yy17SnLfjPrNMTsp5oXbJ1zMQoS41XpnORSG7+GfavhnKYbt0iIDsdp8/ftXlA9HjiRRKlroAV17fdfFvf6AtK80gq9HxK8Loa8WXVjgZcP4Vf5MjKxa60Xt5J1oI+lsxUuXTHkgunLg76WWGy+euo="}

Decoding the pack I have:
{"t":"dev","cid":"f4911e6fcbdf","bc":"000000000000000000000000000000","brand":"gree","catalog":"gree","mac":"f4911e6fcbdf","mid":"10001","model":"gree","name":"1e6fcbdf","series":"gree","vender":"1","ver":"V1.2.1","lock":0}

So we have these values:
cid: f4911e6fcbdf
mac: f4911e6fcbdf
tcid: dc26211e39c8

The question is, which one and in which field I've to use to do a right request?

In any combination I try I didn't get an answer...

Thank you!

**Comment by tomikaa87** [comment]
Hi @4suino,

`cid` contains the ID of the sender, and `tcid` contains the ID of the receiver. They are of course different if you send a packet from one device to another. In most devices, `mac` is used as a device ID. At the moment I'm not aware of any units that use other value for `cid`. You can use the target device's `mac` as `tcid` if you want to send a packet to it, and use the sender device's `mac` as `cid`.

I hope this clarifies things a little bit.

**Comment by 4suino** [comment]
> Hi @4suino,
> 
> `cid` contains the ID of the sender, and `tcid` contains the ID of the receiver. They are of course different if you send a packet from one device to another. In most devices, `mac` is used as a device ID. At the moment I'm not aware of any units that use other value for `cid`. You can use the target device's `mac` as `tcid` if you want to send a packet to it, and use the sender device's `mac` as `cid`.
> 
> If you look your scan response packet of your device, you can find that `"cid":"f4911e6fcbdf"` and `"mac":"f4911e6fcbdf"` has the same value, and `f4911e6fcbdf` is your device's unique ID. If you send a directed packet to this device, you use this ID in the `tcid` field. When the device answers, it uses that ID as `cid`, and `tcid` will be your application's ID that sent the request to the device. `mac` field is not used in request packets, and only be found in device responses.
> 
> I hope this clarifies things a little bit.

Hi, it is more clear.
Now i tried with only tcid. In the cid field there is "app". Correct?
Now the request is:
{ "cid": "app", "i": 1, "pack": "+S7uFVRLOsBzYFTNdYefFVmKn0UCQ7H1JFt0Yos9vCWwFoglpkSudNl/7+i1cZ2m", "t": "pack", "tcid": "f4911e6fcbdf", "uid": 0 }

and the pack value is with empty mac (correct?):
{ "mac": "", "t": "bind", "uid": 0 }

but still no answer from device :(

Thank you

**Comment by 4suino** [comment]
Sorry for the request, could you send me a full bind request string? Thank you

**Comment by tomikaa87** [comment]
> Now i tried with only tcid. In the cid field there is "app". Correct?
> Now the request is:
> { "cid": "app", "i": 1, "pack": "+S7uFVRLOsBzYFTNdYefFVmKn0UCQ7H1JFt0Yos9vCWwFoglpkSudNl/7+i1cZ2m", "t": "pack", "tcid": "f4911e6fcbdf", "uid": 0 }
> 
> and the pack value is with empty mac (correct?):
> { "mac": "", "t": "bind", "uid": 0 }
> 
> but still no answer from device :(
> 
> Thank you

Yes, `app` is correct since it doesn't have a unique ID.
The binding request seems to be correct, but the Pack is missing the `mac` value. If you check the documentation, it must look like this:
```
{
  "mac": "<MAC address of the device you're binding to>",
  "t": "bind",
  "uid": 0
}
```
Just use the value of `tcid` for the `mac` in the Pack.

**Comment by 4suino** [comment]
> > Now i tried with only tcid. In the cid field there is "app". Correct?
> > Now the request is:
> > { "cid": "app", "i": 1, "pack": "+S7uFVRLOsBzYFTNdYefFVmKn0UCQ7H1JFt0Yos9vCWwFoglpkSudNl/7+i1cZ2m", "t": "pack", "tcid": "f4911e6fcbdf", "uid": 0 }
> > and the pack value is with empty mac (correct?):
> > { "mac": "", "t": "bind", "uid": 0 }
> > but still no answer from device :(
> > Thank you
> 
> Yes, `app` is correct since it doesn't have a unique ID.
> The binding request seems to be fine, but the Pack is missing the `mac` value. If you check the documentation, you'll see it must look like this:
> 
> ```
> {
>   "mac": "<MAC address of the device you're binding to>",
>   "t": "bind",
>   "uid": 0
> }
> ```
> 
> Just use the value of `tcid` for the `mac` in the Pack.
> Without the `mac`, the target device won't know that the request is intended for it.

Sorry, I removed the value of mac before because previous I read "mac field is not used in request packets, and only be found in device responses.".
Now I tried with tcid value but still the same issue... no response.

command string: { "cid": "app", "i": 1, "pack": "zQooMsCaOCwK1z80OQb7zXLl/vap1wKRfsiNOElNtbCx2qZW0VI/VP+SRZjZMWtD", "t": "pack", "tcid": "f4911e6fcbdf", "uid": 0 }

and pack: { "mac": "f4911e6fcbdf", "t": "bind", "uid": 0 }

I don't know if can help, I tried to send the command in broadcast and directly to the ip.

Thank you

**Comment by tomikaa87** [comment]
> Sorry, I removed the value of mac before because previous I read "mac field is not used in request packets, and only be found in device responses.".

Sorry, I forgot that Packs use the `mac` field.

> Now I tried with tcid value but still the same issue... no response.
> 
> command string: { "cid": "app", "i": 1, "pack": "zQooMsCaOCwK1z80OQb7zXLl/vap1wKRfsiNOElNtbCx2qZW0VI/VP+SRZjZMWtD", "t": "pack", "tcid": "f4911e6fcbdf", "uid": 0 }
> 
> and pack: { "mac": "f4911e6fcbdf", "t": "bind", "uid": 0 }
> 
> I don't know if can help, I tried to send the command in broadcast and directly to the ip.

For me, the fields seem to be fine.
How do you encrypt the Pack? Do you use AES128 with ECB encoding and PKCS-7 padding? You can set these values in PyCrypto for example.

**Comment by 4suino** [comment]
Yes, I'm using similar code. Have tried with your and the encoded string is the same...
I'm suspecting a different implementation of the air conditioning.
Can you help me with some idea?

**Comment by 4suino** [comment]
Sorry... you have right. My padding routine was wrong.
Thank you for your support!
