### ISSUE TITLE
Cooper&Hunter branded devices with WiFi capacity use this protocol too

### ISSUE THREAD

**Issue by alexiade** [tomikaa87/gree-remote#4]
Just for information :) I went through the wifi capture, got the base packet json and from there google got me to your project. Both of my AC-s are talking to me nicely now :) Thanks!

**Comment by jllcunha** [comment]
If you use OpenHab you might want to checkout my binding (written based on the research from this project)
https://community.openhab.org/t/new-gree-air-conditioner-binding/36429
Good to see that Tamas' work is going further and further :)

**Comment by tomikaa87** [comment]
Currently I don't use it, but will definitely check out. Since I have a growing number of custom made home automation gadgets I'm sure I need to use it soon.

**Comment by alexiade** [comment]
I never got OpenHab to do what I needed and it was killing my old laptop of a server, so I ended up building my own hub on web2py with MQTT as interface layer so hardware side interfaces can be written in whatever... I like snakes :D I even put micropython in my ESP-s :P It's still VERY raw, but if you want to I can put the application on github, once Ive interfaced the AC-is to it :)

**Comment by tomikaa87** [comment]
Maybe I should do the same. Maybe I should convert one of my ESP8266 modules to an IoT hub, with C++ it would take much less flash space after all. ;)

**Comment by alexiade** [comment]
I made a christmas lights blinker that served a reasonably sized web interface - Esps connection handling was so poor, i had to resort to some heavy load phasing to get it to serv up all the resources.

**Comment by alexiade** [comment]
Ive been thinking of using a Rasberry Pi as hub, but the aincent Atom netbook is just too convenient :P it even has built in UPS.

**Comment by tomikaa87** [comment]
Seems to be a suitable job for a Raspberry Pi Zero W then. It only uses about 100 mA (ESP8266 is 70 mA when the WiFi is running) and ten times faster, plus it has a linux kernel.

**Comment by alexiade** [comment]
Have to look into it, I have all three regular variant Pi iterations but not the Zero W :) Yet.

**Comment by tomikaa87** [comment]
Zero W is a cute one, and because of the integrated WiFi module, it virtually needs nothing but stable 5 Volts. :)
