### ISSUE TITLE
TemSen value

### ISSUE THREAD

**Issue by vladsrynty** [tomikaa87/gree-remote#40]
Hello, I need help reading value of TemSen

I have a Gree Device (branded NordCel) with firmware revision 3.1.
TemUn returns 0 (should mean Celsius), but TemSen returns 118.
What could that possibly mean? Even after subtracting -40, it is not a reasonable value.

**Comment by tomikaa87** [comment]
Hi, I you measure the real temperature next to the unit, compare it to `TemSen` and note down the difference, you can see if there is a correlation. Another possibility is that newer firmware operates with fractional numbers and `118` could mean `11.8`. But I'm just guessing. After the measurement it should be more obvious.

**Comment by vladsrynty** [comment]
Strange, et seems it is always 118.

hid returns 36200100077+CS532XV3.1.bin

**Comment by tomikaa87** [comment]
If that's the case, your unit probably doesn't have an internal sensor and the controller reports some random value.

**Comment by vladsrynty** [comment]
That makes sense. Thank you!
