### ISSUE TITLE
Multiple commands with Python script

### ISSUE THREAD

**Issue by dulemis** [tomikaa87/gree-remote#41]
Hi,

How can one send multiple commands in one request? Like the gree apps scenes-feature. One press can turn on the device, set a specific mode and temp.

**Comment by tomikaa87** [comment]
@dulemis 

I've updated the PythonCLI script to accept multiple parameters in bot Get and Set mode, like this:

```
python3 gree.py -i <id> -k <key> -c <ip> set Lig=1 Mod=4 SetTem=26
```

```
python3 gree.py -i <id> -k <key> -c <ip> get Lig Mod SetTem
```
