### ISSUE TITLE
Maximum length for AP password?

### ISSUE THREAD

**Issue by Daniel-K1986** [tomikaa87/gree-remote#50]
Hello,

I can successfully register my AC with the "guest wifi" of a FritzBox, for example:
ssid: "Guest", pw: "1234ABCD"
But I am not able to register my AC with either the main wifi or the guest wifi with a significant longer password (30-40 characters). The response is always
resp={'t': 'ret', 'r': 200, 'mac': 'mac1234'}
The wifi AP of the AC shuts down and comes back up after a few moments.
Are there any restrictions? Or any ideas? I do not want to change my wifi password to a shorter one (this could weaken security and also I am too lazy).

Kind regards,
Daniel

**Comment by tomikaa87** [comment]
Hi @Daniel-K1986,

My network has a 33-characters long password and my AC units can connect to it without problems. Do you have special or accented characters in the password which can't be encoded in plain ASCII?

**Comment by Jc2k** [comment]
@Daniel-K1986 Did you get anywhere with this? I have a similar problem (unit accepts the password, get a 200 response, but the built in comes backup after a minute or so). From what I can see in the network logs it connects but never gets an IP address.

My main wifi is UniFi. I have had devices before (Eve Extend) which were flakey with UniFi but that worked perfectly with FritzBox, so that is a concern. I haven't tried a weaker password yet.

**Comment by Jc2k** [comment]
Ok made a new SSID on my existing WiFi hardware. Insecure 7 letter password worked straight away, trying again with the same test AP and a 32 character password failed. 31 character then worked. All of the passwords were ASCII, lower case, upper case and numbers. So seems like my model has a limit on the password size.

This was an EcoAir rebrand (the crystal mk2).

**Comment by Daniel-K1986** [comment]
Hi,
you were faster... ;-) In the end, I connected the ACs with my guest wifi network. And for that network, I changed the password to 26 characters. If I remember I have tested the maximum length and came up with around 30 characters, same as you.

Kind regards,

Daniel

**Comment by Jc2k** [comment]
Cheers for the reply :) helps me be sure I haven't fat fingered something 🫠

**Comment by tomikaa87** [comment]
Added this issue to the Remarks section of the README.md.
