### ISSUE TITLE
Add support of statuses

### ISSUE THREAD

**Issue by ddenisyuk** [tomikaa87/gree-remote#7]
I've found few extra statuses which can be requested (changed?):
     SlpMod: 0,
     AllErr: 0,
     host: 'eu.dis.gree.com',
     name: 'Livingroom conditioner '

Those statuses were found in SQLite DB of EWPE Smart iOS APP.
Data form "deviceTable" table:
- "fullJson1" column: ["Pow","HeatCoolType","Mod","TemUn","SetTem","TemRec","StHt","SvSt","host","name","AllErr","ModelType"]
- "fullJson2" column: ["Pow","Mod","TemUn","SetTem","TemRec","HeatCoolType","WdSpd","Tur","Quiet","SwUpDn","SwingLfRig","Air","Blo","Health","SvSt","Lig","StHt","SwhSlp","SlpMod","AllErr","ModelType"]

**Comment by ddenisyuk** [comment]
and little bit more:
`
    public static String ACStupPos = "ACStupPos";
    public static String Act = "Act";
    public static String Add0_5 = "Add0.5";
    public static String AdjSet = "AdjSet";
    public static String Air = "Air";
    public static String AirQ = "AirQ";
    public static String AltTmH = "AltTmH";
    public static String AltTmL = "AltTmL";
    public static String AnalFro = "AnalFro";
    public static String AreSel = "AreSel";
    public static String AssHeat = "AssHeat";
    public static String AssHt = "AssHt";
    public static String BarCode = "BarCode";
    public static String Blo = "Blo";
    public static String COAla = "COAla";
    public static String ClnPro = "ClnPro";
    public static String Cloth = "Cloth";
    public static String ClrEr = "ClrEr";
    public static String ClrPro = "ClrPro";
    public static String CoolNoise = "CoolNoise";
    public static String CoolSn = "CoolSn";
    public static String CoolSv = "CoolSv";
    public static String CoolSvStTemMaxH = "CoolSvStTemMaxH";
    public static String CoolSvStTemMaxL = "CoolSvStTemMaxL";
    public static String CoolSvStTemMin = "CoolSvStTemMin";
    public static String CoolSvStTemMinH = "CoolSvStTemMinH";
    public static String CoolSvStTemMinL = "CoolSvStTemMinL";
    public static String CurWD = "CurWD";
    public static String DIYGra1PoiAmo = "DIYGra1PoiAmo";
    public static String DIYGra1Tm1TemH = "Slp1H1";
    public static String DIYGra1Tm1TemL = "Slp1L1";
    public static String DIYGra1Tm2TemH = "Slp1H2";
    public static String DIYGra1Tm2TemL = "Slp1L2";
    public static String DIYGra1Tm3TemH = "Slp1H3";
    public static String DIYGra1Tm3TemL = "Slp1L3";
    public static String DIYGra1Tm4TemH = "Slp1H4";
    public static String DIYGra1Tm4TemL = "Slp1L4";
    public static String DIYGra1Tm5TemH = "Slp1H5";
    public static String DIYGra1Tm5TemL = "Slp1L5";
    public static String DIYGra1Tm6TemH = "Slp1H6";
    public static String DIYGra1Tm6TemL = "Slp1L6";
    public static String DIYGra1Tm7TemH = "Slp1H7";
    public static String DIYGra1Tm7TemL = "Slp1L7";
    public static String DIYGra1Tm8TemH = "Slp1H8";
    public static String DIYGra1Tm8TemL = "Slp1L8";
    public static String DIYGra2PoiAmo = "DIYGra2PoiAmo";
    public static String DIYGra2Tm1TemH = "Slp2H1";
    public static String DIYGra2Tm1TemL = "Slp2L1";
    public static String DIYGra2Tm2TemH = "Slp2H2";
    public static String DIYGra2Tm2TemL = "Slp2L2";
    public static String DIYGra2Tm3TemH = "Slp2H3";
    public static String DIYGra2Tm3TemL = "Slp2L3";
    public static String DIYGra2Tm4TemH = "Slp2H4";
    public static String DIYGra2Tm4TemL = "Slp2L4";
    public static String DIYGra2Tm5TemH = "Slp2H5";
    public static String DIYGra2Tm5TemL = "Slp2L5";
    public static String DIYGra2Tm6TemH = "Slp2H6";
    public static String DIYGra2Tm6TemL = "Slp2L6";
    public static String DIYGra2Tm7TemH = "Slp2H7";
    public static String DIYGra2Tm7TemL = "Slp2L7";
    public static String DIYGra2Tm8TemH = "Slp2H8";
    public static String DIYGra2Tm8TemL = "Slp2L8";
    public static String Dat9_5 = "Dat9.5";
    public static String DevID = "DevID";
    public static String Dfltr = "Dfltr";
    public static String DnPLLRSwing = "DnPLLRSwing";
    public static String DnPRLRSwing = "DnPRLRSwing";
    public static String DnPUDSwing = "DnPUDSwing";
    public static String DsplyEnvWet = "DsplyEnvWet";
    public static String DsplySt = "DsplySt";
    public static String Elc1Kwh = "Elc1Kwh";
    public static String ElcAllKwhClr = "ElcAllKwhClr";
    public static String ElcDatDte = "ElcDatDte";
    public static String ElcDatHor = "ElcDatHor";
    public static String ElcDatMth = "ElcDatMth";
    public static String ElcDteKwh = "ElcDteKwh";
    public static String ElcErg = "ElcErg";
    public static String ElcGear = "ElcGear";
    public static String ElcHorKwh = "ElcHorKwh";
    public static String ElcMthKwh = "ElcMthKwh";
    public static String ElcOnKwh = "ElcOnKwh";
    public static String ElcP = "ElcP";
    public static String Emod = "Emod";
    public static String EnvArea1St = "EnvArea1St";
    public static String EnvArea2St = "EnvArea2St";
    public static String EnvArea3St = "EnvArea3St";
    public static String EnvArea4St = "EnvArea4St";
    public static String EnvArea5St = "EnvArea5St";
    public static String EnvArea6St = "EnvArea6St";
    public static String EnvArea7St = "EnvArea7St";
    public static String EnvArea8St = "EnvArea8St";
    public static String EnvArea9St = "EnvArea9St";
    public static String EnvFun = "EnvFun";
    public static String F0 = PushConstant.GR_Error_F0;
    public static String F1 = PushConstant.GR_Error_F1;
    public static String F2 = PushConstant.GR_Error_F2;
    public static String F3 = PushConstant.GR_Error_F3;
    public static String F4 = PushConstant.GR_Error_F4;
    public static String F5Sd = "F5Sd";
    public static String FIRclmShldSta = "FIRclmShldSta";
    public static String FM = "FM";
    public static String FMSt = "FMSt";
    public static String FMSta = "FMSta";
    public static String FbidBloPer = "FbidBloPer";
    public static String FlSta = "FlSta";
    public static String FlTemH = "FlTemH";
    public static String FlTemL = "FlTemL";
    public static String ForcFun = "ForcFun";
    public static String GEA = "GEA";
    public static String GetEr = "GetEr";
    public static String HasTmr = "HasTmr";
    public static String Health = "Health";
    public static String HeatCoolType = "HeatCoolType";
    public static String HeatNoise = "HeatNoise";
    public static String HeatSvStTemMax = "HeatSvStTemMax";
    public static String HotFl = "HotFl";
    public static String HotSn = "HotSn";
    public static String HotSv = "HotSv";
    public static String HumSen = "HumSen";
    public static String HumiSvStTemMin = "HumiSvStTemMin";
    public static String ImagRec = "ImagRec";
    public static String LTemDry = "LTemDry";
    public static String Led = "LedLig";
    public static String Lig = "Lig";
    public static String LigInt = "LigInt";
    public static String LigSta = "LigSta";
    public static String LigSty = "LigSty";
    public static String MafIdf = "MafIdf";
    public static String MasIDUMod = "MasIDUMod";
    public static String MasSub = "MasSub";
    public static String Mod = "Mod";
    public static String MusicNm = "MusicNm";
    public static String NoiseSet = "NoiseSet";
    public static String PM = "PM";
    public static String PM2P5 = "PM2P5";
    public static String Pow = "Pow";
    public static String PowVolHLim = "PowVolHLim";
    public static String PowVolLLim = "PowVolLLim";
    public static String Purify = "Purify";
    public static String Quiet = "Quiet";
    public static String RmotCtrKeySig = "RmotCtrKeySig";
    public static String RmotCtrSend = "RmotCtrSend";
    public static String RoomHigh = "RoomHigh";
    public static String RoomLen = "RoomLen";
    public static String RoomWid = "RoomWid";
    public static String RtvTemH = "RtvTemH";
    public static String RtvTemL = "RtvTemL";
    public static String SaveGuid = "SaveGuid";
    public static String SetTem = "SetTem";
    public static String ShldNatCon = "ShldNatCon";
    public static String SlpGra3EndHor = "SlpGra3EndHor";
    public static String SlpGra3EndMin = "SlpGra3EndMin";
    public static String SlpGra3StaHor = "SlpGra3StaHor";
    public static String SlpGra3StaMin = "SlpGra3StaMin";
    public static String SlpMod = "SlpMod";
    public static String SpaAmnt = "SpaAmnt";
    public static String StHt = "StHt";
    public static String StTemH = "StTemH";
    public static String StTemL = "StTemL";
    public static String SvSt = "SvSt";
    public static String SwUpDn = "SwUpDn";
    public static String SwhComp = "SwhComp";
    public static String SwhComp2 = "SwhComp2";
    public static String SwhDIYGra1 = "SwhDIYGra1";
    public static String SwhDIYGra2 = "SwhDIYGra2";
    public static String SwhDry = "SwhDry";
    public static String SwhEleHtup1 = "SwhEleHtup1";
    public static String SwhEleHtup2 = "SwhEleHtup2";
    public static String SwhEnvSim = "SwhEnvSim";
    public static String SwhFil = "SwhFil";
    public static String SwhFreAir = "SwhFreAir";
    public static String SwhFreAirVal = "SwhFreAirVal";
    public static String SwhInMot = "SwhInMot";
    public static String SwhInMot2 = "SwhInMot2";
    public static String SwhOutMot = "SwhOutMot";
    public static String SwhOutMot2 = "SwhOutMot2";
    public static String SwhPMW = "SwhPMW";
    public static String SwhSlp = "SwhSlp";
    public static String SwhSw = "SwhSw";
    public static String SwhWet = "SwhWet";
    public static String SwhWifi = "SwhWifi";
    public static String SwhWifiConf = "SwhWifiConf";
    public static String SwhWifiRes = "SwhWifiRes";
    public static String SwhWkup = "SwhWkup";
    public static String SwingLfRig = "SwingLfRig";
    public static String TemRec = "TemRec";
    public static String TemSen = "TemSen";
    public static String TemUn = "TemUn";
    public static String TmrDecDig = "TmrDecDig";
    public static String TmrLpTms = "TmrLpTms";
    public static String TmrOff = "TmrOff";
    public static String TmrOffFunc = "TmrOffFunc";
    public static String TmrOffSdHor = "TmrOffSdHor";
    public static String TmrOffSdMin = "TmrOffSdMin";
    public static String TmrOffSt = "TmrOffSt";
    public static String TmrOffWD0 = "TmrOffWD0";
    public static String TmrOffWD1 = "TmrOffWD1";
    public static String TmrOffWD2 = "TmrOffWD2";
    public static String TmrOffWD3 = "TmrOffWD3";
    public static String TmrOffWD4 = "TmrOffWD4";
    public static String TmrOffWD5 = "TmrOffWD5";
    public static String TmrOffWD6 = "TmrOffWD6";
    public static String TmrOn = "TmrOn";
    public static String TmrOnFunc = "TmrOnFunc";
    public static String TmrOnSdHor = "TmrOnSdHor";
    public static String TmrOnSdMin = "TmrOnSdMin";
    public static String TmrOnSt = "TmrOnSt";
    public static String TmrOnWD0 = "TmrOnWD0";
    public static String TmrOnWD1 = "TmrOnWD1";
    public static String TmrOnWD2 = "TmrOnWD2";
    public static String TmrOnWD3 = "TmrOnWD3";
    public static String TmrOnWD4 = "TmrOnWD4";
    public static String TmrOnWD5 = "TmrOnWD5";
    public static String TmrOnWD6 = "TmrOnWD6";
    public static String TmrOneDig = "TmrOneDig";
    public static String TmrTenDig1 = "TmrTenDig1";
    public static String TmrTenDig2 = "TmrTenDig2";
    public static String Tur = "Tur";
    public static String UDFanPort = "UDFanPort";
    public static String WatTmp = "WatTmp";
    public static String WdFocusHum = "WdFocusHum";
    public static String WdGr = "WdGr";
    public static String WdSpd = "WdSpd";
    public static String Werr = "Werr";
    public static String Wet = "Wet";
    public static String Wind = "Wind";
    public static String WkupStaHor = "WkupStaHor";
    public static String WkupStaMin = "WkupStaMin";
    public static String WkupTmHor = "WkupTmHor";
    public static String WkupTmMin = "WkupTmMin";
    public static String Wmod = "Wmod";
    public static String WschOff = "WschOff";
    public static String WschOffMin = "WschOffMin";
    public static String WschOn = "WschOn";
    public static String WschOnMin = "WschOnMin";
    public static String WsenNub = "WsenNub";
    public static String WsenTmpH = "WsenTmpH";
    public static String WsenTmpL = "WsenTmpL";
    public static String WsenTmpM = "WsenTmpM";
    public static String WsetTmp = "WsetTmp";
    public static String WstpH = "WstpH";
    public static String WstpSv = "WstpSv";
    public static String Wtmr1 = "Wtmr1";
    public static String Wtmr1Min = "Wtmr1Min";
    public static String Wtmr2 = "Wtmr2";
    public static String Wtmr2Min = "Wtmr2Min";
    public static String Wtmr3 = "Wtmr3";
    public static String Wtmr3Min = "Wtmr3Min";
    public static String deviceLock = "lock";
    public static String deviceName = "name";
    public static String deviceTime = "time";
    public static String deviceVersion = "hid";
    public static String host = "host";
    public static String strBacWdHumHLim = "strBacWdHumHLim";
    public static String strBacWdHumLLim = "strBacWdHumLLim";
    public static String strCurTmHor = "strCurTmHor";
    public static String strCurTmMin = "strCurTmMin";
    public static String strHum = "strHum";
    public static String strHumPre = "strHumPre";
    public static String strTemPre = "strTemPre";
    public static String strTmrOffHorLf = "strTmrOffHorLf";
    public static String strTmrOffMinLf = "strTmrOffMinLf";
    public static String strTmrOnHorLf = "strTmrOnHorLf";
    public static String strTmrOnMinLf = "strTmrOnMinLf";
    public static String strTmrOn_OffTmLf = "strTmrOn/OffTmLf";
`

**Comment by tomikaa87** [comment]
Thank you, I'll test this on my device and add to the documentation and to the libraries.

**Comment by grunci** [comment]
Hi @tomikaa87,
It seems, that **TemSen** is the temperature in the room in celsius, plus 40
So if there is 24 celsius in the room, the response will be 64.
I guess they didn't want to handle negative numbers, so -40 is 0. (Just an assumption)

**Comment by tomikaa87** [comment]
> 
> 
> Hi @tomikaa87,
> It seems, that **TemSen** is the temperature in the room in celsius, plus 40
> So if there is 24 celsius in the room, the response will be 64.
> I guess they didn't want to handle negative numbers, so -40 is 0. (Just an assumption)

Hi, I've checked, it seems to be working on my device as well.
