### ISSUE TITLE
New repo

### ISSUE THREAD

**Issue by alexmuntean** [tomikaa87/gree-remote#8]
Hi guys,

I used your repo to read how to do the binding and stuff.. I created a rest API. I'm using this to create applets on IFTTT mostly for google assistant :)
I'll document it later and add your repository as source of inspiration if that's fine for you.
repo: https://github.com/alexmuntean/gree-airconditioner-rest
It's a spring boot project. if you wanna see it just `mvn clean install` and `java -jar target/....jar" and you'll see the REST API in `localhost:8080/powerOn` `localhost:8080/powerOff` `localhost:8080/temperature?temperature=16`

Thanks for your contribution and research and patience :)

Thanks,
Alex

**Comment by tomikaa87** [comment]
Thank you! I've added your repo's URL to the README.
